### PR TITLE
Hola for Chrome detection

### PR DESCRIPTION
**Pull request by charliwest**
Detects is the Hola 'vpn' add-on is installed

### CODE REVIEW

**Comment by YesThatAllen** [comment]
Is Hola VPN universally bad, or just unwanted in some settings?

**Comment by charliwest** [comment]
http://adios-hola.org
They sell the bandwidth of their users to the highest bidder, with no regard to what they do with it.

**Comment by sheagcraig** [comment]
Also, I would argue that the users of SavingThrow are going to be almost exclusively enterprise/education users. I'm guessing it's not being used to manage individual machines. And I would think that users installing VPN's like this, probably to circumvent something they shouldn't be, would be universally frowned upon by their admins.

**Comment by YesThatAllen** [comment]
Agreed. If people don't want to remove Hola, they just don't add this ADF .. problem solved.

A case for more categorization of kinds of Malware, as time allows.

**Pull request merged**
